### ISSUE TITLE
twitch-unit-test

### ISSUE THREAD

**Issue by PaulieScanlon** [PaulieScanlon/mdx-embed#121]
Hooray 🎉 thanks for your interest in [MDX Embed](https://mdx-embed.com) 

If you'd like to contribute by writing this test please have a read of: 

- The [Umbrella Issue](https://github.com/PaulieScanlon/mdx-embed/issues/71) 
- The [Acceptance Criteria](https://github.com/PaulieScanlon/mdx-embed/issues/71#acceptance-criteria) for **Unit Tests**

**Comment by ekafyi** [comment]
Hi folks! 👋

As we discussed in the [party-corgi hacktoberfest channel](https://discordapp.com/channels/601625579166367755/745364186346815610/762004299953471498), I have created the following three tests:

- 'it renders the component when provided a twitchId' -- `<Twitch parent="http://localhost:6006/" twitchId="679474192" />`
- 'it renders the component when provided a channel' -- `<Twitch parent="http://localhost:6006/" channel="jlengstorf" />`
- 'it renders the component when provided a collection' -- `<Twitch parent="http://localhost:6006/" collection="eMybriFryRWpiQ" />`

Here is the code: https://github.com/ekafyi/mdx-embed/blob/test/twitch-unit/packages/mdx-embed/src/components/twitch/twitch.test.tsx

The tests (`yarn test`) all passed.

Is it good for PR or should anything be changed?

Thanks!

**Comment by PaulieScanlon** [comment]
Hey @ekafyi Thanks for this. It's a little hard to review as it stands. Would you mind creating a PR and i'll add my review there. 

One note however. There's a utility function we've created that provides a mock intersection observer and a method that exposes a mock "scrolled in to view" event so you won't need to do add this yourself.

There's more here on how to setup [unit testing](https://github.com/PaulieScanlon/mdx-embed/blob/main/CONTRIBUTING.md#unit-testing) the `triggerGeneralObserver` method has been globally exposed so it's available in all `jest` files... no need to import it see the [Codepen](https://github.com/PaulieScanlon/mdx-embed/blob/main/packages/mdx-embed/src/components/codepen/codepen.test.tsx) test
