### ISSUE TITLE
storybook-addon-mdx-embed

### ISSUE THREAD

**Issue by PaulieScanlon** [PaulieScanlon/mdx-embed#138]
**Is your feature request related to a problem? Please describe.**
[Dom](https://twitter.com/domyen) from Storybook has been in contact asking if there was an easy way to use MDX Embed with Storybook / docs. There is and it's the way we use it for the [docs site](https://mdx-embed.com) but it is a little tricky to setup.

**Describe the solution you'd like**
Ideally MDX Embed would create a package that lives in this repo e.g `packages/storybook-addon-mdx-embed` which once installed with `@storybook/react` : `^6.0.0` + `@storybook/addon-docs` would enable 3rd party embeds in any Storybook `.mdx` file

**Describe alternatives you've considered**
The alternative solution to the addon is for MDX Embed to provide documentation for how setup Storybook for use with MDX Embed.

A minimal setup might look like this:

```javascript 
// preview.js

import React from 'react';
import { addParameters } from '@storybook/react';
import { DocsContainer } from '@storybook/addon-docs/blocks';

import { MDXEmbedProvider } from 'mdx-embed';

addParameters({
  docs: {
    container: ({ children, context }) => (
      <DocsContainer context={context}>
            <MDXEmbedProvider>{children}</MDXEmbedProvider>
      </DocsContainer>
    ),
  },
});

```

**Additional context**
I've looked over the various Storybook [api](https://storybook.js.org/docs/react/api/addons-api)'s but i think in most cases its only possible to add an Addons Panel. I think in this case what we need to is to wrap the `docs` page element with the `MDXEmbedProvider` which is kind of what the `addParameters` code snippet above is doing. I'd like to establish if any of the current Storybook api methods can be used in this way.

For reference this method of "wrapping" page elements is how we're able to provide MDX Embed to Gatsby MDX pages:
Gatsby expose a [wrapRootElement](https://www.gatsbyjs.com/docs/browser-apis/#wrapRootElement) method which we use to wrap all MDX content with `MDXEmbedProvider` - see [here](https://github.com/PaulieScanlon/mdx-embed/blob/main/packages/gatsby-plugin-mdx-embed/gatsby-browser.js)

**Comment by PaulieScanlon** [comment]
I've pinged Michael in the Storybook Discord channel and sent him a link to this issue. Excited to see if it's going to be possible... hang tight.

**Comment by shilman** [comment]
@PaulieScanlon yes this is possible. we don't have an API for it per se (we might want to add it in the future?), but you can achieve this with standard Storybook APIs.

The preset should add a `config` entry that adds the parameters, and possibly registers the addon in the manager (only if the addon needs registering -- I don't think that's needed in this case). Example here:

https://github.com/storybookjs/storybook/blob/next/addons/backgrounds/src/preset/index.ts

Assuming your snippet above is correct, the parameters declaration would look like this:

```
import React from 'react';
import { DocsContainer } from '@storybook/addon-docs/blocks';
import { MDXEmbedProvider } from 'mdx-embed';

export const parameters = {
  docs: {
    container:  ({ children, context }) => (
      <DocsContainer context={context}>
            <MDXEmbedProvider>{children}</MDXEmbedProvider>
      </DocsContainer>
    ),
  }
}
```

Example:

https://github.com/storybookjs/storybook/blob/next/addons/backgrounds/src/preset/defaultParameters.tsx

This parameter will get hierarchically merged into the existing parameters, meaning that as long as your addon is listed *AFTER* `addon-docs` in `main.js`, it should override it and you should be in business.

Let me know if you have any questions!

**Comment by PaulieScanlon** [comment]
@shilman Wow! thanks Michael! This super helpful! It's given me a few things to investigate but its great to know this kind of thing is going to be possible!! Mega stuff, and i'll no doubt be in touch if i have any further questions!

Thanks again!!

**Comment by PaulieScanlon** [comment]
@shilman Hi again... i've made _some_ progress... no errors which is a good thing but i don't think i'm exporting the preset correctly or in fact if anything i'm doing is correct here but, below is a demo repo i've been tinkering with.

**Demo Repo**
[storybook-preset-mdx-embed](https://github.com/PaulieScanlon/storybook-preset-mdx-embed)

The `docs` workspace is a standard Storybook (React) setup with the following dependancies
- `@storybook/addon-docs`
- `mdx-embed` 
- `mdx-embed-preset` 

The config in `main.js` looks like this 👇

```javascript
module.exports = {
  stories: ['../stories/**/*.stories.mdx'],
  addons: ['@storybook/addon-docs', 'mdx-embed-preset']
};

```

The `mdx-embed-preset` workspace has the following

- `src/index.js`
- `src/preset.js` 

and both are  transpilled to `dist`

- `dist/index.js`
- `dis/preset.js`

**mdx-embed-preset/src/preset.js**
The below is what i have in  `src/preset.js`

```javascript
// src/preset.js

import React from 'react';
import { DocsContainer } from '@storybook/addon-docs/blocks';
import { MDXEmbedProvider } from 'mdx-embed';

const parameters = {
  docs: {
    container: ({ children, context }) => (
      <DocsContainer context={context}>
        <div id="test-div" style={{ border: '3px solid red' }}>
          <MDXEmbedProvider>{children}</MDXEmbedProvider>
        </div>
      </DocsContainer>
    )
  }
};

export function config(entry) {
  return [...entry, parameters];
}

```

I've tried it with and without the config export and with and without the parameters set to export. Is there any `entry` thing i'm missing or perhaps a naming convention, and do i need a `register.js` in there for this to work?

**Comment by shilman** [comment]
You need two separate files. One that exports a config entry pointing to the second. And the second file  that exports a `parameters` object. You're trying to combine them into one, but it won't work that way. Use addon-backgrounds as a template.

**Comment by PaulieScanlon** [comment]
@shilman Boogy time, it worked!!!! 

This is so cool, and apologies, i did see you comments about `addon-background` and missed the bit about separating the parameters and config exports.

<img width="1341" alt="Screenshot 2020-09-22 at 13 38 57" src="https://user-images.githubusercontent.com/1465706/93883082-fdd5bc80-fcd8-11ea-8a53-077a18f43b90.png">

**Comment by shilman** [comment]
Woohoo!!! 🥰

**Comment by PaulieScanlon** [comment]
@shilman no worries at all mate! One last question.... naming things is hard. Would the convention (before i release it on npm) for this package be

```
storybook-preset-mdx-embed
```

**Comment by shilman** [comment]
Thanks for checking. We switched conventions mid stream. Originally we distinguished presets and addons and there's still some leftovers from that. Now everything's an addon and presets are just a mechanism for helping addons configure themselves. 

So this is an addon and I'd keep your original name!

**Comment by PaulieScanlon** [comment]
@shilman lovely stuff so...

```
storybook-addon-mdx-embed
```

**Comment by PaulieScanlon** [comment]
completed in [#139 ]
