### ISSUE TITLE
Cypress on WSL

### ISSUE THREAD

**Issue by NickyMeuleman** [PaulieScanlon/mdx-embed#160]
**Describe the bug**
Testing with Cypress errors on Windows for users of the Windows Subsystem for Linux

**To Reproduce**
1. Set up this repo
2. run `yarn cy:test`

**Expected behavior**
Cypress opens in the GUI and runs the tests.

**Screenshots**
See the Hacktoberfest overview video @PaulieScanlon and @spences10 did https://youtu.be/TzWm_tullLo?t=921

**Desktop (please complete the following information):**
 - OS: Windows 10 using WSL

**Additional context**
I ran into this issue and explained how to overcome it in a blogpost at https://nickymeuleman.netlify.app/blog/gui-on-wsl2-cypress

Thanks for mentioning it on Twitter Scott!
https://twitter.com/spences10/status/1312059000817692672

Would you like me to add a mention about what to do in the docs?
(yay for possible Hacktoberfest PRs 🎉 )

**Comment by PaulieScanlon** [comment]
@NickyMeuleman Hey mate, this is great! Yeah!! if you're up for creating a PR you could maybe add something in the [CONTRIBUTING.md](https://github.com/PaulieScanlon/mdx-embed/blob/main/CONTRIBUTING.md#integration-tests) somewhere near the *integration-test* details. i'll add a Hacktoberfest label on the PR and you might get your hands on a t-shirt!
