### ISSUE TITLE
Whimsical component

### ISSUE THREAD

**Issue by amercier** [PaulieScanlon/mdx-embed#179]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Would you be interested in [Whimsical](https://whimsical.com/) support? It is a great solution for technical diagrams, so it would fit perfectly in Storybook scenarios, for instance.

Here's a API proposal:

```mdx
<Whimsical
  publicLink="https://whimsical.com/ELbgAN9VUHXfwghKqH72KA"
  ratio="1:3"
/>
```

With:
- `ratio` to be provided by user (defaults to `1:1`)
- `publicLink` to be copied directly from Whimsical:
![image](https://user-images.githubusercontent.com/1246795/95979622-2f473100-0e1c-11eb-99ba-d3eb159522e4.png). Alternatively this could by `diagramId` or `chartId` being `ELbgAN9VUHXfwghKqH72KA` in this case.

**Note:** I could try working on a PR if you confirm that you would be inclined to merge in the end.

**Describe alternatives you've considered**

- Using generated images from Whimsical, but you'd have to copy/paste/save on every change, not very dynamic
- Using a plain link, no images :'(

**Additional context**

It is already integrated in [Notion](https://www.notion.so/) for instance, where it looks pretty neat:

![example-whimsical](https://user-images.githubusercontent.com/1246795/95979423-e7280e80-0e1b-11eb-853a-4f520aa4099f.gif)

**Comment by spences10** [comment]
Hey @amercier this looks great, yeah, by all means make a PR.

If you're feeling up to it create the integration and unit tests as well otherwise we can add them to the Hacktoberfest Umbrella Issue (#71)

Many thanks 👍
