### ISSUE TITLE
Detail the project being part of Hacktoberfest 2020

### ISSUE THREAD

**Issue by spences10** [PaulieScanlon/mdx-embed#209]
This image is taken from [Tails]

![image](https://user-images.githubusercontent.com/234708/97971776-768d6580-1dbb-11eb-9b58-5967e95223ec.png)

May be a good idea to add something similar to the storybook site

[Tails]:https://devdojo.com/tails

**Comment by PaulieScanlon** [comment]
@spences10 would we have to say this project "was" part of Hacktoberfest 2020?

**Comment by spences10** [comment]
> @spences10 would we have to say this project "was" part of Hacktoberfest 2020?

Don't think we _have_ to say, but thought it gives a good indication of it being a welcoming GitHub community project

**Comment by PaulieScanlon** [comment]
@spences10 yeah got ya, was just curious about what tense to use.

**Comment by spences10** [comment]
> @spences10 yeah got ya, was just curious about what tense to use.

What about _intense_!??

![](http://www.reactiongifs.com/r/wds.gif)
