### ISSUE TITLE
mdx-embed: You must install peer dependencies yourself for react@17.x.x

### ISSUE THREAD

**Issue by sgmheyhey** [PaulieScanlon/mdx-embed#210]
**Describe the bug**
```
npm WARN mdx-embed@0.0.14 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN mdx-embed@0.0.14 requires a peer of react-dom@^16.13.1 but none is installed. You must install peer dependencies yourself.
```

with react@17.x.x, the messages are produced. it seems working but the messages should be cleared.

**Comment by PaulieScanlon** [comment]
Is the problem here that you needed to install React? React is a peer dependancy. Could you elaborate a bit and I’d be happy to investigate

**Comment by sgmheyhey** [comment]
```
  "dependencies": {
    "mdx-embed": "latest",
    "next": "latest",
    "prism-react-renderer": "latest",
    "react": "latest",
    "react-dom": "latest",
    "react-live": "latest"
}
```
The part of my `package.json` file was like the above.

**Comment by PaulieScanlon** [comment]
Hi @sgmheyhey i still don't really understand the problem. If you've installed the peer dependancies you should be fine. Is your Next project setup to use MDX, i don't see `@next/mdx` in your deps.

I'll close this issue but feel free to open one again if you're still having problems.

**Comment by sgmheyhey** [comment]
Sorry, I've just edited the above comment.

**Comment by PaulieScanlon** [comment]
@sgmheyhey could you maybe try installing the peer deps as version numbers: Here's what MDX Embed wants as [peerDependencies](https://github.com/PaulieScanlon/mdx-embed/blob/main/packages/mdx-embed/package.json#L77)

```javascript
  "peerDependencies": {
    "@mdx-js/mdx": "^1.6.16",
    "@mdx-js/react": "^1.6.16",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
```

**Comment by sgmheyhey** [comment]
They're gone! Thank you!

**Comment by PaulieScanlon** [comment]
Ok great! 

I think the problem was MDX Embed has a peer dependancy of "react: ^16.x.x" and you had installed "react: latest" which would have installed "react 17.x.x". 

The difference between "16.x.x." and "17.x.x" with regard to semver is "breaking" so i think there's probably something in "react 17.x.x." that doesn't work with MDX Embed... 

...but that's ok. MDX Embed does specify that it's "react: 16.x.x" you need to install not "react: latest" or "react: 17.x.x."

**Comment by danielmarin0051** [comment]
@PaulieScanlon is there any plan to support react 17 in the future?
