### ISSUE TITLE
Instagram Component

### ISSUE THREAD

**Issue by nickwild-999** [PaulieScanlon/mdx-embed#225]
Thanks for a great library. What is the best way to change the width of the Instagram component?

**Comment by PaulieScanlon** [comment]
Hey @nickwild-999 thanks for the issue. Unfortunately i don't think Instagram provide a way to do this via their embed code. We try not to mess with anything unless it's be exposed as an option from the provider. If you do find Instagram provide a way to do this with their embed code please do let us know but for now i'll close this issue.

**Comment by spences10** [comment]
Hey @PaulieScanlon maybe this is a good use case for adding a discussion tab to the project, this could have been asked as a question using the discussions feature rather than an issue. What do you think?
