### ISSUE TITLE
[Feature-Request] Render RAW files from GITHUB, like MD files

### ISSUE THREAD

**Issue by ebellumat** [PaulieScanlon/mdx-embed#226]
**Is your feature request related to a problem? Please describe.**
I want to create a story with my dependencies list on storybook, example: https://github.com/SConaway/react-native-credit-card-display/blob/master/README.md

I want to render this README.MD on that story without have to copy and paste this MD source code. 

A iframe embed would be cool. 

**Describe the solution you'd like**
A component for any url on iFrame maybe or a component specific for Github MD files. 

**Describe alternatives you've considered**
Copy and paste the MD code into my Storybook 🥲

**Additional context**
![image](https://user-images.githubusercontent.com/26942680/116164071-6f427700-a6cf-11eb-9720-9093b59ea361.png)

**Comment by PaulieScanlon** [comment]
Hey @ebellumat Whilst this is a nice idea i don't think GitHub offer an embeddable solution. MDX Embed unifies Embed services that already exist. We do have an embed component for [Gists](https://www.mdx-embed.com/?path=/docs/components-gist--usage). That's about all we can do at the moment until GitHub create an embed code... on that note if they have please do open another feature request and we'll look into it.

**Comment by spences10** [comment]
You could render the `.md` file using MDX @ebellumat 

Like what @PaulieScanlon said though, that's not in the scope of this project.
