### ISSUE TITLE
Gatsby v4 

### ISSUE THREAD

**Issue by just-andy** [PaulieScanlon/mdx-embed#236]
**Is your feature request related to a problem? Please describe.**
It would be great to see the plugin work with Gatsby v4

**Describe the solution you'd like**
Installed the plugin but getting a dependency issue that this plugin only works with gatsby v3.2

**Additional context**
error in build

_warn Plugin gatsby-plugin-mdx-embed is not compatible with your gatsby version 4.0.1 - It requires gatsby@^3.2.0_

**Comment by PaulieScanlon** [comment]
Hi @just-andy i've just released `0.0.23` which has support for Gatsby 4. Lemme know how you get on.
