### ISSUE TITLE
Custom Loader

### ISSUE THREAD

**Issue by thatanjan** [PaulieScanlon/mdx-embed#241]
When I embed something like Tweet, I only see `loading` text before it gets loaded.
How can I add a custom Loading component to display on the page?

Thanks in advance.

**Comment by spences10** [comment]
You'll need to add in your spinner/loading component into the other side of the turnery function here: https://github.com/PaulieScanlon/mdx-embed/blob/3d56d5771f6d17f4b78543e6a836648232acb976/packages/mdx-embed/src/components/twitter/tweet.tsx#L31

Or for whatever component you want to show a spinner for.

Thanks

**Comment by thatanjan** [comment]
Thank you so much @spences10
