### ISSUE TITLE
MDX-Embed website is down 

### ISSUE THREAD

**Issue by lwildermuth** [PaulieScanlon/mdx-embed#252]
Seems the website and docs are down.

**Comment by lacymorrow** [comment]
Do you guys plan on supporting this library? It's fantastic and I don't think it should die...

**Comment by lacymorrow** [comment]
@PaulieScanlon @spences10

**Comment by spences10** [comment]
hey @lacymorrow the domain has expired, personally I've not done anything with Gatsby in over three years now

You'll still be able to run the docs locally, or read it from the repo

**Comment by lacymorrow** [comment]
@spences10 would you be willing to create a domain on vercel or something? Or transfer the info into the github Readme?

I would be willing to take over maintaining the repo if you want, currently there are no docs.

**Comment by PaulieScanlon** [comment]
Hey @lacymorrow, here's the default Netlify link if you need access to the docs: https://mdx-embed.netlify.app

**Comment by lacymorrow** [comment]
Awesome 😎  @PaulieScanlon , may be work pasting that into the readme.

I've been adding mdx-embed to other projects but it's hard to describe to others exactly what it does without the demo site.

**Comment by PaulieScanlon** [comment]
Hey @lacymorrow, all links have now been changed. and i've redeployed the docs site. 

It'll always be here now: https://mdx-embed.netlify.app/

**Comment by lacymorrow** [comment]
@PaulieScanlon You're the man, thank you. 

I know I'm annoying but without any accessible documentation I could see this project dying, and it's been super useful for me in a number of things.

I've made pull requests to add it to Nextra.site and Nextbook

**Comment by PaulieScanlon** [comment]
It has been a good project, i wish i could devote a bit more time to it. It needs a bit of love, MDX 2 support for instance. You're enthusiasm has kinda spurred me on a bit though so, thanks!

I'll keep an eye out for the PR and review it when it's ready.

**Comment by lacymorrow** [comment]
@PaulieScanlon would you be interested in onboarding a few new maintainers? I don't have a lot of extra time but I'm happy to keep things updated and fix a few issues occasionally.
