### ISSUE TITLE
Twitch Optional TwitchId

### ISSUE THREAD

**Issue by PaulieScanlon** [PaulieScanlon/mdx-embed#63]
The `twitchId` prop has been made optional so that the component can work if you wish to use it for channel or collection but the url string still attempts to insert it even though it could be `undefined` The URL string should probably be constructed in a better way so that if `twitchId` isn't provided it won't get added

Similar sort of issue with the `title` in the iFrame where we use  ` title={`twitch-${twitchId}`}` which would also be undefined if the prop isn't provided.

**Comment by daisygabi** [comment]
Hi, I would like to work on this. I am stuck on how to add the libraries locally so I can work on the change in code. I tried firstly adding 'gatsby-plugin-mdx-embed' as a local plugin but needing mdx-embed (where the modification would be like) I thought that I` yarn build` after each modification and add the binaries in node_modules of the gatsby project would work. But it doesn't.

I must say i didn't work with gatsby before but I have no issues learning while doing. Can you point me to the correct way to work with mdx-embed locally? 

After I get this done, I would like to contribute to the Readme file of the project because I needed some more info as well. Thanks! :)

**Comment by PaulieScanlon** [comment]
Hey Gabi, you're very welcome to give this a go. I'd suggest forking this repo. 

Once you have it locally you can run `yarn` or `npm i` to install all the dependencies then you can run `yarn storybook` or `npm run storybook` which will spin up our Storybook development environment. Once you're happy with the changes feel free to create a PR.

**Comment by daisygabi** [comment]
> Hey @daisygabi, you're very welcome to give this a go. I'd suggest forking this repo.
> 
> Once you have it locally you can run `yarn` or `npm i` to install all the dependencies then you can run `yarn storybook` or `npm run storybook` which will spin up our Storybook development environment. Once you're happy with the changes feel free to create a PR.

Hi, I have stumbled upon a new error trying to run `yarn storybook` (below is the stack trace for reference). In that .preview.js IntelliJ is warning me that "import { MDXEmbedProvider } from 'mdx-embed';" mdx-embed is not found, even though it does exist in the packages folder. If you have some pointers, it will help. Thanks.

`ERROR in ./.storybook/preview.js
Module not found: Error: Can't resolve 'mdx-embed' in 'D:\workspace-frontend\mdx-embed\docs\.storybook'
 @ ./.storybook/preview.js 14:0-45 26:42-58
 @ ./.storybook/preview.js-generated-config-entry.js
 @ multi ../node_modules/@storybook/core/dist/server/common/polyfills.js ../node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ../node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-e
ntry.js ../node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js ../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInf
o=undefined
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.34 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [../node_modules/html-webpack-plugin/lib/loader.js!../node_modules/@storybook/core/dist/server/templates/index.ejs] 2.12 KiB {HtmlWebpackPlugin_0} [built]

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

webpack building...
webpack built c92d15443d102737c489 in 279ms
× ｢wdm｣: Hash: c92d15443d102737c489
Version: webpack 4.44.1
Time: 279ms
Built at: 09/04/2020 3:01:57 PM
                                          Asset      Size        Chunks                                      Chunk Names
           3c2bde6a3411d95f6b14.hot-update.json  35 bytes                [emitted] [immutable] [hmr]
                                    iframe.html  2.97 KiB                [emitted]
            main.c92d15443d102737c489.bundle.js   555 KiB          main  [emitted] [immutable]        [big]  main
        main.c92d15443d102737c489.bundle.js.map   218 KiB          main  [emitted] [dev]                     main
    runtime~main.c92d15443d102737c489.bundle.js  33.5 KiB  runtime~main  [emitted] [immutable]               runtime~main
runtime~main.c92d15443d102737c489.bundle.js.map  34.7 KiB  runtime~main  [emitted] [dev]                     runtime~main
    vendors~main.c92d15443d102737c489.bundle.js  2.04 MiB  vendors~main  [emitted] [immutable]        [big]  vendors~main
vendors~main.c92d15443d102737c489.bundle.js.map  1.97 MiB  vendors~main  [emitted] [dev]                     vendors~main
Entrypoint main [big] = runtime~main.c92d15443d102737c489.bundle.js runtime~main.c92d15443d102737c489.bundle.js.map vendors~main.c92d15443d102737c489.bundle.js vendors~main.c92d15443d102737c489.bundle.js.map main.c92d15443d102737c489.bundle.js main.c92d15443d102737c489.b
undle.js.map
[0] multi ../node_modules/@storybook/core/dist/server/common/polyfills.js ../node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ../node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-
entry.js ../node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js ../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noIn
fo=undefined 112 bytes {main}
[../node_modules/@storybook/addon-docs/dist/frameworks/common/config.js] 521 bytes {vendors~main}
[../node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js] 2.24 KiB {vendors~main} [built]
[../node_modules/@storybook/addon-docs/dist/frameworks/react/config.js] 758 bytes {vendors~main}
[../node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js] 2.24 KiB {vendors~main} [built]
[../node_modules/@storybook/client-api/dist/index.js] 4.99 KiB {vendors~main}
[../node_modules/@storybook/client-logger/dist/index.js] 3.66 KiB {vendors~main}
[../node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main}
[../node_modules/@storybook/core/dist/server/preview/globals.js] 93 bytes {vendors~main}
[../node_modules/@storybook/react/dist/client/index.js] 1.88 KiB {vendors~main}
[../node_modules/airbnb-js-shims/index.js] delegated ./airbnb-js-shims/index.js from dll-reference storybook_docs_dll 42 bytes {main}
[../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined] 7.68 KiB {vendors~main}
[./.storybook/generated-stories-entry.js] 295 bytes {main} [built]
[./.storybook/preview.js-generated-config-entry.js] 2.82 KiB {main} [built]
[./.storybook/storybook-init-framework-entry.js] 26 bytes {main} [built]
    + 523 hidden modules

ERROR in ./.storybook/preview.js
Module not found: Error: Can't resolve 'mdx-embed' in 'D:\workspace-frontend\mdx-embed\docs\.storybook'
 @ ./.storybook/preview.js 14:0-45 26:42-58
 @ ./.storybook/preview.js-generated-config-entry.js
 @ multi ../node_modules/@storybook/core/dist/server/common/polyfills.js ../node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ../node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-e
ntry.js ../node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js ../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInf
o=undefined
`

**Comment by PaulieScanlon** [comment]
@daisygabi Hey, sorry there is one more thing you'll need to do after installing the dependancies... apologies i should have mentioned this earlier... if you run `yarn build` or `npm run build` that will create the `mdx-embed` `dist` directory in `packages/mdx-embed`... i'll make a note to add that to our contribution guide!

**Comment by PaulieScanlon** [comment]
resolved in [#68](https://github.com/PaulieScanlon/mdx-embed/pull/68)
