### ISSUE TITLE
Why is gatsby v 2.24.50 a peer dependency?

### ISSUE THREAD

**Issue by ehowey** [PaulieScanlon/mdx-embed#69]
**Describe the bug**
When installing mdx-embed I get a warning:

```shell
warning " > gatsby-plugin-mdx-embed@0.0.10" has unmet peer dependency "gatsby@^2.24.50".
```
Is there a reason you need such a recent version of Gatsby or can you back out to an earlier version?

**Comment by PaulieScanlon** [comment]
@ehowey that's a good question. I think in my haste to migrate this i just left it as the version installed by default. This can probably be a must earlier version since there's nothing really to the plugin. Leave it with me and i'll change that in the next release. Ty for letting us know!

**Comment by PaulieScanlon** [comment]
drop Gatsby dep in PR [#70](https://github.com/PaulieScanlon/mdx-embed/pull/70)

**Comment by ehowey** [comment]
Nice thanks Paul. Figured that was the case but didn’t want to merge until I was sure as I am not on that release of Gatsby yet!
