### ISSUE TITLE
Stream run down

### ISSUE THREAD

**Issue by PaulieScanlon** [PaulieScanlon/mdx-embed#79]
Ahoy @spences10.

In preparation for "The Big Stream" which i'm primarily thinking will help us out for Hacktoberfest but could also be useful to record and pop somewhere for future reference i'd like to run through how to get started with contributing to the project.

Not necessarily in this order but here's some things i think we should try and cover on stream

- Forking the repo
- Install dependancies
- Run the build (just the once is enough)
- Quickly go over the dir structure
- Quickly go over the scripts in the root `package.json`
- Explain how we use Storybook to develop
- Just point out where the Contrib doc is in the repo

But the main thing i'd like to cover because i think this is where we can create a number of issues and label them Hacktoberfest is how to test the components. 

Each component will probably require a unit test. This are most likely just going to be one test for "it renders the component" as per the CodePen example

Then once we've worked out how to do it i'd like to cover off the Cypress integration tests.

Then anyone who wants to contribute can claim a test or perhaps claim both the unit and integration test, we'll add their name next to the component in the [umbrella issue](https://github.com/PaulieScanlon/mdx-embed/issues/71) and see where we go from there.

How's that sound?

**Comment by PaulieScanlon** [comment]
Whey!!! we did it!

**Comment by spences10** [comment]
Here's the video: https://www.youtube.com/watch?v=TzWm_tullLo

Can you add it to the issue pls @PaulieScanlon 🙏
