### ISSUE TITLE
404 page being overridden

### ISSUE THREAD

**Issue by zslabs** [PaulieScanlon/mdx-embed#83]
**Describe the bug**
👋 Can https://github.com/PaulieScanlon/mdx-embed/blob/main/packages/gatsby-plugin-mdx-embed/src/pages/404.js be removed? I'm not sure of its purpose, but this is overriding the default 404 page on my site. I reverted to `@pauliescanlon/gatsby-mdx-embed` that doesn't have this to resolve the issue. 

cc @PaulieScanlon 

**To Reproduce**
1. Install Gatsby package.
2. Visit 404 page
3. Should show custom `pages/404.js` 
4. Shows plugin's 404 instead of custom one.

**Comment by PaulieScanlon** [comment]
@zslabs Hey, thanks for opening the issue and yes... that 404 page shouldn’t be part of the package. In fact I don’t think there should even be a ‘src/pages’ dir at all... unless Gatsby throws errors?

Leave it with me and I’ll sort it and release an update shortly.

**Comment by PaulieScanlon** [comment]
PR raised: [#84 ]

**Comment by zslabs** [comment]
Great, thanks! I agree, there shouldn't be a need for the src folder at all. Appreciate you taking a look!

**Comment by PaulieScanlon** [comment]
Resolved by [#84]

**Comment by PaulieScanlon** [comment]
@zslabs Hey mate, i've just released `v0.0.13`... lucky for some!

Would you mind upgrading and letting me know if it's sorted... i'l keep the issue open for now.

**Comment by zslabs** [comment]
@PaulieScanlon Yep that did it, thanks!
